### ISSUE TITLE
Change costumes when winning a battle in Locke's scenario

### ISSUE THREAD

**Issue by abyssonym** [abyssonym/beyondchaos#65]
Some people don't know about the hidden passage across the river, so this part might be confusing for them.

**Comment by abyssonym** [comment]
decided to implement this, after all

**Comment by Tenkarider** [comment]
So at the really end what will you change?

**Comment by abyssonym** [comment]
It's already done. At the end of the battle with Merchant or Officer, you take their costume, as though you stole it from them. It's a very minor change, but a lot of people were getting stuck in that part.
