### ISSUE TITLE
Windows and Python version producing different result

### ISSUE THREAD

**Issue by abyssonym** [abyssonym/beyondchaos#72]
The Windows version appears to be very glitchy. Need to investigate.

**Comment by abyssonym** [comment]
I'm embarrassed that this went unnoticed for so long, but it should be fixed now. The Windows executable and the python script both generate the exact same file, and the graphical errors I was seeing before are gone too.

**Comment by Tenkarider** [comment]
What kind of errors? my l'il bro did the last run with windows...

**Comment by abyssonym** [comment]
I think it was mostly just graphical errors. Garbage data was written into palettes and the result was really ugly.
