### ISSUE TITLE
Zone Eater chests inaccessible

### ISSUE THREAD

**Issue by sorlok** [abyssonym/beyondchaos#74]
The chests inside the Zone Eater that require jumping seem to be inaccessible:
https://beeimg.com/images/m60261274902.png

...because there are no triggers to jump down. Is this intentional?

**Comment by abyssonym** [comment]
Unfortunately yes, in the ancient cave, all events from non-kefka's tower maps have been removed. I might reintroduce events in a future update but it would require a lot of effort and testing, so don't expect it any time soon.

**Comment by sorlok** [comment]
'k, no worries. It's already a really sweet mod as-is. :)
