### ISSUE TITLE
"Shadow" cloned character runs from party

### ISSUE THREAD

**Issue by sorlok** [abyssonym/beyondchaos#75]
Hello!

Playing through an Ancient Cave run:
https://youtu.be/xS_KCSrc2Do?t=18m56s

I get a Shadow-cloned character (looks like Relm), and she immediately jumps ship after the next battle. She then re-appears the next time I enter the room (and I can get her back in the party).

My question: is this intentional, and is it possible to get her to stay in the party permanently?

**Comment by abyssonym** [comment]
It's not possible to get her to stay permanently. This is a new game mechanic for the cave that I've been experimenting with, and might decide to remove.

**Comment by sorlok** [comment]
Ah, ok. That's kind of an interesting mechanic, but I think you should add it to the readme. :)
