### ISSUE TITLE
Possibly unwinnable seed (tracked to possible error room)

### ISSUE THREAD

**Issue by sorlok** [abyssonym/beyondchaos#76]
**Edit**: After poking around in a FF3 map editor, this map (311) is definitely not the problem, but the map remains unwinnable. I'll diagram the rest of the map and update this bug report.

**Original report**: 
The seed 1456002672 with settings "ancientcave" seems to have no path for the first party. 

I tracked this through the script a bit, and ended up at room 311:

Location: 311 (name: Collapsing House)
   Entrances:
       <311 ?: 102 53> ; dest: 4a South Figaro (World of Ruin) => 74 (name: South Figaro (WoR))
       <311 ?: 126 22> ; dest: 57 => 87 (name: South Figaro Basement)

The entrance I came in from was (126,22: South Figaro Basement). However, this room (the final floor of the collapsing house, where you find the child hiding) definitely only has one exit (unless you hacked in another one somewhere). 

It is possible that something else is causing this path to be broken, but I tracked every other room and this seems to be the only anomaly. 

Picture of the area:
http://cubeupload.com/im/NDjWZd.png

**Comment by sorlok** [comment]
Wow, I feel like a dummy. Despite this being one of my favorite games, I never knew about this room:
http://i.cubeupload.com/SvRZqe.png

One of these days I'll find a real bug in Beyond Chaos, but so far I've got to say I'm very impressed with the stability of the project!

**Comment by abyssonym** [comment]
Yeah, the map indexes don't necessarily stay the same in the game data, so it can be difficult to troubleshoot. Don't worry though... there's plenty of bugs still left to find. :)
