### ISSUE TITLE
Windows Defender thinks beyondchaos.exe is a Trojan

### ISSUE THREAD

**Issue by Shokushu** [abyssonym/beyondchaos#83]
![image](https://user-images.githubusercontent.com/6484427/30925681-aa36c9d4-a380-11e7-916e-2853eb065022.png)

I also got a warning for a Perl backdoor when I cloned the repo.

Do you know what causes this?

**Comment by abyssonym** [comment]
Any antivirus program is expected to have a high rate of false positives. Considering that the randomizer executable contains an entire Python interpreter and requires permission to create and modify files, I'm not surprised that an antivirus program might flag it for being similar to some malware.

If you're still concerned, you can install Python on your Windows machine and use that to run the Python version. The full source code of the Python version is available to read, so you can be confident that it's not installing any trojans on your system.

**Comment by abyssonym** [comment]
As for the Perl backdoor, there's no Perl code anywhere in the repo, either (I don't speak it). The program I use to create the executable is "pyinstaller", and that's probably what's triggering the malware warnings.

**Comment by Shokushu** [comment]
Thanks for the clarification, I have no doubts that you wouldn't put a backdoor in this, just wanted to tell you =)
