### ISSUE TITLE
unwinnable seed

### ISSUE THREAD

**Issue by wompwompa** [abyssonym/beyondchaos#85]
Using seed: 62.zbmetfspda.1511018731

so im in mobliz in the WoB and still havent come across dried meat.. none for sale anywhere yet and nobody on the veldt can drop it..  cant get gau without it, so im stuck i think.. unless anybody can come up with a solution?    

anywho ive played through two other random seeds and i love it.. thanks for making this amazing game even better and fresher.. the random kefka tower, and random final battle party is a real cool twist

**Comment by abyssonym** [comment]
Thanks for letting me know. I can see the problem with that particular flag combination; the shops are randomized but Gau won't be automatically recruited, so you are indeed stuck. If you want to continue the seed, you could try using cheat codes to obtain Dried Meat or use the save file with a vanilla rom to buy some and then switch back to the randomized rom.
